In [30]:
import numpy as np

In [31]:
import sympy as sm
import scipy as sc
from scipy.linalg import expm

In [53]:
#Solving the problem statement as mentioned in Presentation
#The matrix A obtained is
A = np.array([[1, 0.5, 0],[0, 0.5, 1], [0,0,0]])  
x0 = np.array([1/3, 1/3, 1/3])   #initial frequency

In [40]:
type(x0)

numpy.ndarray

In [41]:
Y = sm.Matrix(A)
print(Y)
P,D = Y.diagonalize()   # Y = PDP^-1 it returns P and D

Matrix([[1.00000000000000, 0.500000000000000, 0.0], [0.0, 0.500000000000000, 1.00000000000000], [0.0, 0.0, 0.0]])


In [42]:
P

Matrix([
[1.0, -1.0,  0.5],
[  0,  1.0, -1.0],
[  0,    0,  0.5]])

In [43]:
D

Matrix([
[1.0,   0, 0],
[  0, 0.5, 0],
[  0,   0, 0]])

In [44]:
D1 = np.array(D)
n = sm.symbols('n')
D2 =(D1)**n

In [45]:
D2

array([[1.0**n, 0**n, 0**n],
       [0**n, 0.5**n, 0**n],
       [0**n, 0**n, 0**n]], dtype=object)

In [46]:
from numpy.linalg import inv
P1 = np.array(P)
B = (P1)@(D2)@(inv(P1.astype(float)))

In [47]:
B

array([[-0.5*0**n + 1.0*1.0**n, 1.0*0**n - 1.0*0.5**n + 1.0*1.0**n,
        3.5*0**n - 2.0*0.5**n + 1.0*1.0**n],
       [0, -1.0*0**n + 1.0*0.5**n, -2.0*0**n + 2.0*0.5**n],
       [0.5*0**n, 1.0*0**n, 2.5*0**n]], dtype=object)

In [48]:
xn = B@x0
xn

array([1.33333333333333*0**n - 1.0*0.5**n + 1.0*1.0**n,
       -1.0*0**n + 1.0*0.5**n, 1.33333333333333*0**n], dtype=object)

In [49]:
from sympy import limit, oo
l = []
for i in range(0,3):
  l.append(limit(xn[i],n, oo))

In [50]:
r = np.array(l)
print(r)

[1.00000000000000 0 0]


In [52]:
# an (after n generations) has frequency 1 (Genetype with dominating Gene R)